### ISSUE TITLE
Cool logo

### ISSUE THREAD

**Issue by vadymmarkov** [hyperoslo/Imaginary#2]
@RamonGilabert I believe in you.

**Comment by RamonGilabert** [comment]
Added a label.

**Comment by sindrenm** [comment]
Haha!

**Comment by sindrenm** [comment]
Added in https://github.com/hyperoslo/Imaginary/commit/84644b2a2fcd6900773bb8f62b85666804a37379.

**Comment by vadymmarkov** [comment]
@sindrenm ❤️
