### ISSUE TITLE
Feature an image manager

### ISSUE THREAD

**Issue by zenangst** [hyperoslo/Imaginary#36]
I think it could be interesting to introduce a `manager` (I don't know the proper name for this). But essentially it would be a struct or class that can be used to preload images before they would appear on screen. So as you scroll, the images would already be pre-loaded. Would this be doable with the current setup?

**Comment by zenangst** [comment]
What are your thoughts on this @vadymmarkov @onmyway133 @RamonGilabert

**Comment by vadymmarkov** [comment]
@zenangst Interesting idea, but how do we know how many images should be loaded when we have pagination for example? And I think cells appear before images are loaded, so we need to find a way to notify them about this update. Or I'm missing something? 😄

**Comment by zenangst** [comment]
If we intercept the payload and start loading them right away in sequence, wouldn't the `Fetcher` pick up on that and fetch it from `Cache` if they exist? Or do you mean that you might end up fetching them twice?

**Comment by vadymmarkov** [comment]
I think it could happen that we fetch them twice, in first cells for example.

**Comment by onmyway133** [comment]
Or we can expose `Fetcher`? So that users can call it at their convenience? Like when they are about to go to a screen, and want to fetch the first several images?

**Comment by vadymmarkov** [comment]
I think the idea is to not fetch images in cells, right @zenangst? So we should find some smart way to fetch them after we get data from a backend, but before we render table/collection views with image views on cells. But at the same time we don't want to wait until all the images are loaded and cached. So image loading in this image manager and UI rendering should work in parallel somehow, and without double fetching ideally.

**Comment by onmyway133** [comment]
@zenangst @vadymmarkov `Imaginary 3` now has standalone `ImageFetcher` and `MultipleImageFetcher`. I think We should close this for now
