### ISSUE TITLE
Feature request: Gif support

### ISSUE THREAD

**Issue by chosa91** [hyperoslo/Imaginary#51]
Hy, 

Is it possible to pass back (NS)Data (officially) to be capable to handle Gif images too?

**Comment by zenangst** [comment]
Hey @chosa91, right now we don't aim to support gifs in Imaginary. Can't really make any promises if we are gonna support this in the future either. We just don't need it at the moment. I imagine (pun intended) that it would introduce quiet a lot of complexity by adding this kind of feature.
