### ISSUE TITLE
Error in doc and internal protection level

### ISSUE THREAD

**Issue by skrew** [hyperoslo/Imaginary#66]
Hi,

In the Readme:
```
let downloader = ImageDownloder()
downloader.download(url: imageUrl) { result in
  // handle result
}
```
Have to be replaced by `ImageDownloader()`

Also, the `.download` function is inaccessible (internal protection level)

**Comment by onmyway133** [comment]
@skrew Hi, thanks for your report. We will fix it here https://github.com/hyperoslo/Imaginary/pull/68
