### ISSUE TITLE
Does the library support the usage of an authorization header?

### ISSUE THREAD

**Issue by lmsmartins** [hyperoslo/Imaginary#74]
Does the library support the usage of an authorization header when fetching the image from an URL?

**Comment by onmyway133** [comment]
@SnitramDev It hasn't, we will work on a fix for this

**Comment by onmyway133** [comment]
@SnitramDev Hi, this PR has just been merged https://github.com/hyperoslo/Imaginary/pull/76. Can you point to master and see if you can use `modifyRequest` closure on `Option`? See README for more info.

**Comment by lmsmartins** [comment]
How could I use this in the Lightbox Controller?



            let images = [
                LightboxImage(
                    imageURL: URL(string: "https://static.wixstatic.com/media/b77fe464cfc445da9003a5383a3e1acf.jpg")!,
                    text: "testing.jpg"
                )
            ]

            // Create an instance of LightboxController.
            let controller = LightboxController(images: images)

            // Set delegates.
            controller.downloadSuccessDelegate = self
            controller.downloadFailDelegate = self

            // Use dynamic background.
            controller.dynamicBackground = true

            // Present your controller.
            present(controller, animated: true, completion: nil)
