### ISSUE TITLE
Is it possible to use an authentication header in the request?

### ISSUE THREAD

**Issue by lmsmartins** [hyperoslo/Imaginary#77]
Is it possible to use an authentication header in the request?

**Comment by onmyway133** [comment]
Possible duplication of https://github.com/hyperoslo/Imaginary/issues/74. Starting from https://github.com/hyperoslo/Imaginary/releases/tag/3.0.3 you can now customise how the request is made. See https://github.com/hyperoslo/Imaginary#downloading
