### ISSUE TITLE
Path to image location on disk

### ISSUE THREAD

**Issue by AndreiVidrasco** [hyperoslo/Imaginary#82]
Hi,

I'm using this great framework for a Cocoa(Mac) Application and I want to implement Quick Look Panel(like in Finder). To do so, I just need to provide URL via delegate, but unfortunately for only local files. I want to delegate the task of downloading to Imaginary and to use provide cached path to Quick Look.

Is there a that result from this snippet will actually include path?
```
let fetcher = ImageFetcher(downloader: ImageDownloader(), storage: myStorage()
fetcher.fetch(url: imageUrl) { result in
  // handle result
}
```

Thanks

**Comment by onmyway133** [comment]
@AndreiVidrasco I think we can embed custom metadata to `result`
