### ISSUE TITLE
Is it possible to configure the cache key?

### ISSUE THREAD

**Issue by mgrider** [hyperoslo/Imaginary#94]
I think what's happening is that the API I'm writing against returns different URLs for the same image. (They are unique to the session.) But I know they are the same image, as they are associated with a resource on the server. I'd like to be able to specify the cache key somehow, so that I can still cache these images. Is this possible?

Thank you!

**Comment by mgrider** [comment]
I'm seeing `url.absoluteString` used all over the internals of Imaginary, so I think the answer is no. I will still probably use `Cache`, but I don't think Imaginary (as much as I love the name) will work for my project.

**Comment by 3lvis** [comment]
Sorry for the lack of response but I'm glad you got your problem solved.
