### ISSUE TITLE
Build fails (at least when using Swift Package Manager)

### ISSUE THREAD

**Issue by dc-nrx** [hyperoslo/Imaginary#97]
I'm adding Lightbox via SPM (from master branch) which in turn uses Imaginary. But when I try to build the project an error occurs (please see the screenshot).
It's in ImageFetcher.swift, lines 48 and 50.

<img width="1159" alt="Screenshot 2020-12-09 at 14 27 22" src="https://user-images.githubusercontent.com/10939199/101630082-0c578880-3a2b-11eb-826c-9d99403ac17d.png">

**Comment by 3lvis** [comment]
Solved, thanks.
